services:
  spark-master:
    build:
      context: .
      dockerfile: Dockerfile
      target: jupyter-base
    image: spark-image
    container_name: spark-master
    entrypoint: ["/opt/spark/entrypoint.sh", "master"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 5s
      timeout: 3s
      retries: 3
    env_file:
      - ./.env.spark
    volumes:
      - shared-workspace:/opt/workspace
      - ./data:/opt/workspace/data
      - ./notebooks:/opt/workspace/notebooks
      - ./spark-logs:/opt/spark/spark-events
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
    networks:
      - spark

  spark-worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: jupyter-base
    image: spark-image
    container_name: spark-worker
    entrypoint: ["/opt/spark/entrypoint.sh", "worker"]
    depends_on:
      - spark-master
    env_file:
      - ./.env.spark
    volumes:
      - shared-workspace:/opt/workspace
      - ./data:/opt/workspace/data
      - ./spark-logs:/opt/spark/spark-events
    networks:
      - spark

  spark-history-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: jupyter-base
    image: spark-image
    container_name: spark-history
    entrypoint: ["/opt/spark/entrypoint.sh", "history"]
    depends_on:
      - spark-master
    env_file:
      - ./.env.spark
    volumes:
      - shared-workspace:/opt/workspace
      - ./data:/opt/workspace/data
      - ./spark-logs:/opt/spark/spark-events
    ports:
      - "18080:18080"
    networks:
      - spark

  jupyter:
    build:                      # <-- ОЦЕ ГОЛОВНИЙ ФІКС
      context: .
      dockerfile: Dockerfile
      target: jupyter-base
    image: spark-image
    container_name: jupyter
    depends_on:
      - spark-master
    env_file:
      - ./.env.spark
    volumes:
      - shared-workspace:/opt/workspace
      - ./data:/opt/workspace/data
      - ./notebooks:/opt/workspace/notebooks
      - ./spark-logs:/opt/spark/spark-events
    ports:
      - "8889:8889"
    networks:
      - spark

    entrypoint: []
    command:
      - jupyter
      - lab
      - --no-browser
      - --allow-root
      - --ip=0.0.0.0
      - --port=8889
      - --ServerApp.token=
      - --ServerApp.password=

networks:
  spark:
    driver: bridge

volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local